new_tab datomic
cd ~/Projects/maverick
launch zsh -c "/Users/darth10/.local/share/mise/shims/bb datomic-dev-transactor"

new_tab aws-vault
launch zsh -c "/opt/homebrew/bin/aws-vault exec --ec2-server preprod --debug"
focus

new_tab cljsbuild
cd ~/Projects/maverick
launch --hold  zsh -c "/Users/darth10/.local/share/mise/shims/bb cljs-auto"

new_tab
cd ~/Projects/maverick
launch zsh
